Repository CSE-210-Team-10/cse210-group10, pull requests merged in 2024-12, with the labels that each got.

#60 documentation-adrs-cicd-meghana
  admin/adrs/0011-unit-testing-jest.md
  admin/adrs/0012-packaging-terser.md
  admin/adrs/0013-doc-generation-jsdoc.md
  admin/adrs/0014-remove-htmlhint-stylelint.md
  admin/adrs/0015-integration-testing-cypress.md
  admin/documentation/cipipeline/cicd.md
  admin/meeting-notes/team-meetings/11.27.24 Meeting Notes.md
  admin/meeting-notes/team-meetings/11.29.24 Meeting Notes.md
Labels: documentation

#61 basicframework-david
  .github/workflows/release-pr.yml
  .github/workflows/release.yml
  .gitignore
  dist/.gitignore
  eslint.config.js
  package-lock.json
  package.json
  rollup.config.css.js
  rollup.config.js.js
  scripts/build.py
  scripts/build.sh
  scripts/dev-build.sh
  src/.gitignore
  src/calendar/index.html
  src/calendar/style.css
  src/index.html
  src/js/library.js
  src/pages/index.html
  src/pages/index.js
  src/pages/login/index.html
  src/pages/login/index.js
  src/pages/login/style.css
  src/pages/style.css
  src/styles/root.css
  test/calendar/index.test.js
  test/library.test.js
Labels: enhancement

#76 home-page-design-david
  package-lock.json
  package.json
  rollup.config.css.js
  scripts/build.sh
  src/pages/all-tasks.css
  src/pages/index.html
  src/pages/style.css
  src/static/github-mark-white.svg
  src/static/github-mark.svg
  src/styles/root.css
Labels: enhancement

#78 SSO Integration for Authentication
  eslint.config.js
  jsconfig.json
  package-lock.json
  package.json
  src/js/auth.js
  src/js/supabase.js
  src/pages/index.html
  src/pages/index.js
  src/pages/login/index.html
  src/pages/login/index.js
  src/static/favicon.png
  src/static/favicon.svg
  type.d.ts
Labels: enhancement

#82 Hotfix: An Auth Bug
  src/js/auth.js
Labels: bug

#77 documentation-meeting-notes-cicd-meghana
  admin/adrs/0014-remove-htmlhint-stylelint.md
  admin/adrs/0014-remove-stylelint.md
  admin/documentation/cipipeline/cicd.md
  admin/documentation/cipipeline/cicd.png
  admin/meeting-notes/sprint-retrospectives/12.04.24-sprint3-retrospective.md
  admin/meeting-notes/sprint-reviews/12.04.24-sprint3-review.md
  admin/meeting-notes/team-meetings/12.04.24 Meeting Notes.md
Labels: documentation

#84 hotfix-auth-bug-david
  src/js/auth.js
  src/js/const.js
  src/js/github-api.js
  src/js/local-storage.js
  src/pages/index.js
  src/pages/login/index.js
Labels: bug

#79 mock-tasks-task-filtering-methods-charles
  src/mock/mock-tasks.json
Labels: enhancement

#87 adrs-cicd-github-task-related-shayan
  admin/adrs/0016-python-cicd.md
  admin/adrs/0017-pulling-github-org-data.md
Labels: documentation

#91 task-custom-component-design-david
  scripts/build.py
  src/components/task/index.js
  src/components/task/style.css
  src/components/task/template.html
  src/pages/all-tasks.css
  src/pages/index.html
  src/pages/style.css
  src/styles/root.css
Labels: enhancement

#93 add-github-integration-with-sso-matthew
  src/pages/index.js
Labels: enhancement

#96 task-item-implementation-david
  scripts/build.py
  src/components/task-item/component.css
  src/components/task-item/index.js
  src/components/task-item/template.html
  src/components/task/index.js
  src/components/task/template.html
  src/pages/all-tasks.css
  src/pages/index.html
  src/pages/index.js
  src/pages/style.css
Labels: enhancement

#97 add-linting-standards-eslint-meghana
  admin/documentation/standards/linting-standards.md
Labels: documentation

#116 modernized-scrollbar-and-moved-functions-matthew
  admin/documentation/standards/linting-standards.md
  package-lock.json
  src/js/github-api.js
  src/pages/index.js
  src/pages/style.css
Labels: enhancement

#98 task-filtering-sorting-implementation-charles
  src/utils/task-filtering.js
  test/task-filtering.test.js
Labels: enhancement

#122 home-page-design-implementation-david
  scripts/build.sh
  src/components/task-item/component.css
  src/components/task-item/index.js
  src/components/task-item/template.html
  src/pages/all-tasks.css
  src/pages/index.html
  src/pages/style.css
  src/pages/upcoming-deadlines.css
  src/static/logo.svg
  src/styles/root.css
Labels: enhancement

#135 filters-david
  src/components/filter-form/component.css
  src/components/filter-form/index.js
  src/components/filter-form/template.html
  src/components/task-form/component.css
  src/components/task-form/template.html
  src/js/task/filter.js
  src/pages/filters-state.js
  src/pages/filters.js
  src/pages/index.html
  src/pages/index.js
  src/pages/render.js
  src/pages/upcoming-deadlines.css
  src/styles/root.css
Labels: enhancement

#125 add-linting-standards-htmlhint-and-adr-chatgpt-meghana
  admin/adrs/0018-chatgpt-openai-calls.md
  admin/documentation/standards/linting-standards.md
  admin/meeting-notes/team-meetings/12.07.24 Meeting Notes.md
Labels: documentation

#133 dark-mode-charles
  src/components/task-item/component.css
  src/pages/index.html
  src/pages/index.js
  src/pages/style.css
  src/styles/root.css
Labels: enhancement

#139 Create 0019-remove-codacy.md
  admin/adrs/0019-remove-codacy.md
Labels: documentation

#141 parse-json-into-task-object-github-matthew
  .github/workflows/auto-merge.yaml
  src/js/github-api.js
Labels: enhancement

#143 sync-with-main-team
  .github/workflows/auto-merge.yaml
  .htmlhintrc
  admin/adrs/0018-chatgpt-openai-calls.md
  admin/adrs/0019-remove-codacy.md
  admin/documentation/standards/linting-standards.md
  admin/meeting-notes/team-meetings/12.07.24 Meeting Notes.md
  eslint.config.js
  package-lock.json
  package.json
  scripts/build.sh
  src/components/filter-form/component.css
  src/components/filter-form/index.js
  src/components/filter-form/template.html
  src/components/task-form/component.css
  src/components/task-form/index.js
  src/components/task-form/template.html
  src/components/task-item/component.css
  src/components/task-item/index.js
  src/components/task-item/template.html
  src/js/const.js
  src/js/github-api.js
  src/js/local-storage.js
  src/js/task/crud.js
  src/js/task/filter.js
  src/js/task/index.js
  src/pages/all-tasks.css
  src/pages/filters-state.js
  src/pages/filters.js
  src/pages/index.html
  src/pages/index.js
  src/pages/login/index.html
  src/pages/render.js
  src/pages/style.css
  src/pages/upcoming-deadlines.css
  src/static/logo.svg
  src/styles/root.css
  src/utils/task-filtering.js
  test/task-filtering.test.js
Labels: enhancement

#142 github-issues-and-prs-filter-by-login-username-matthew
  src/js/github-api.js
Labels: enhancement

#134 signout-button-kayla
  package-lock.json
  package.json
  scripts/build.py
  src/mock/mock-personal-tasks.json
  src/pages/index.html
  src/pages/index.js
  test/task-crud.test.js
  type.d.ts
Labels: enhancement

#144 github-task-functionality-david
  src/components/task-item/component.css
  src/components/task-item/index.js
  src/components/task-item/template.html
  src/js/const.js
  src/js/github-api.js
  src/js/local-storage.js
  src/js/task/crud.js
  src/js/task/filter.js
  src/pages/index.html
  src/pages/index.js
  src/pages/render.js
Labels: enhancement

#137 custom-links-sravanthi
  src/pages/chatbot/index.html
  src/pages/index.html
  src/pages/index.js
  src/pages/style.css
  src/static/Add Square 04.png
  src/static/Bookmark.png
  src/static/Link.png
  src/static/Vector.png
  src/static/Web.png
  src/static/duck.png
  src/static/styles.css
Labels: enhancement

#174 upcoming-deadlines-and-date-bug-and-crud-unit-test-kayla
  package.json
  src/components/filter-form/template.html
  src/components/task-form/template.html
  src/components/task-item/template.html
  src/js/task/crud.js
  src/pages/index.html
  src/pages/index.js
  test/task-crud.test.js
Labels: bug, enhancement

#186 remove-upcoming-deadlines-kayla
  src/pages/index.html
  src/pages/index.js
Labels: enhancement

#187 dark-mode-bug-fixes-charles
  src/components/filter-form/component.css
  src/pages/style.css
Labels: enhancement

#173 added-chatbot-functionality
  .gitignore
  package-lock.json
  src/js/chatbot.js
  src/pages/chatbot/index.html
  src/pages/chatbot/index.js
Labels: enhancement

#188 filter-upcoming-deadlines-kayla
  src/pages/index.js
  src/pages/upcoming-deadlines.css
Labels: enhancement

#190 sync-with-main-team
  .github/workflows/release-pr.yml
  .gitignore
  cypress.config.mjs
  cypress.env.json
  cypress/e2e/spec.cy.js
  package-lock.json
  package.json
  scripts/build.py
  src/components/filter-form/component.css
  src/components/filter-form/template.html
  src/components/task-form/component.css
  src/components/task-form/template.html
  src/components/task-item/component.css
  src/components/task-item/index.js
  src/components/task-item/template.html
  src/js/chatbot.js
  src/js/const.js
  src/js/github-api.js
  src/js/local-storage.js
  src/js/task/crud.js
  src/js/task/filter.js
  src/mock/mock-personal-tasks.json
  src/pages/chatbot/index.html
  src/pages/chatbot/index.js
  src/pages/index.html
  src/pages/index.js
  src/pages/login/mock/mock-tasks.json
  src/pages/render.js
  src/pages/style.css
  src/pages/upcoming-deadlines.css
  src/static/Add Square 04.png
  src/static/Bookmark.png
  src/static/Link.png
  src/static/Vector.png
  src/static/Web.png
  src/static/duck.png
  src/static/styles.css
  src/styles/root.css
  test/task-crud.test.js
  test/task-filtering.test.js
  type.d.ts
Labels: enhancement

#157 added-adrs-notes-documentation-meghana
  README.md
  admin/adrs/0021-groq-api-calls.md
  admin/adrs/0022-choosing-mpa.md
  admin/adrs/0023-using-aws-lambda.md
  admin/documentation/cipipeline/cicd.md
  admin/documentation/future-works.md
  admin/documentation/onboarding.md
  admin/meeting-notes/sprint-retrospectives/12.11.24-sprint4-retrospective.md
  admin/meeting-notes/sprint-reviews/11.15.24-sprint1-review.md
  admin/meeting-notes/sprint-reviews/11.23.24-sprint2-review.md
  admin/meeting-notes/sprint-reviews/12.04.24-sprint3-review.md
  admin/meeting-notes/sprint-reviews/12.11.24-sprint4-review.md
  admin/meeting-notes/team-meetings/12.11.24 Meeting Notes.md
  admin/user-feedback/outside-feedback.md
  admin/user-feedback/team-2-feedback.md
Labels: documentation

#201 aws-lambda-documentation-shayan
  admin/documentation/aws-lambda/chatbot-lambda-integration.md
  admin/documentation/onboarding.md
  admin/user-feedback/outside-feedback.md
  admin/user-feedback/team-2-feedback.md
Labels: documentation

#200 updated-readme-last-cleaning-meghana
  README.md
Labels: documentation

#202 release-to-main-team
  README.md
  admin/adrs/0020-use-of-supabase.md
  admin/adrs/0021-groq-api-calls.md
  admin/adrs/0022-choosing-mpa.md
  admin/adrs/0023-using-aws-lambda.md
  admin/documentation/aws-lambda/chatbot-lambda-integration.md
  admin/documentation/cipipeline/cicd.md
  admin/documentation/future-works.md
  admin/documentation/onboarding.md
  admin/meeting-notes/sprint-retrospectives/12.11.24-sprint4-retrospective.md
  admin/meeting-notes/sprint-reviews/11.15.24-sprint1-review.md
  admin/meeting-notes/sprint-reviews/11.23.24-sprint2-review.md
  admin/meeting-notes/sprint-reviews/12.04.24-sprint3-review.md
  admin/meeting-notes/sprint-reviews/12.11.24-sprint4-review.md
  admin/meeting-notes/team-meetings/12.11.24 Meeting Notes.md
  admin/user-feedback/outside-feedback.md
  admin/user-feedback/team-2-feedback.md
Labels: documentation
